name: frontend
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0  # Updated to the latest version
  cupertino_icons: ^1.0.8
  lottie: ^2.3.2
  animated_splash_screen: ^1.3.0
  firebase_core: ^3.13.0

  #FaceDetection + SmartCrop
  image: ^4.1.3
  path_provider: ^2.1.1

  font_awesome_flutter: ^10.7.0

  material_design_icons_flutter: ^6.0.6595

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/authentication/
    - assets/animation/
    - assets/images/others/
    - assets/images/photoposted/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter/Inter_18pt-Bold.ttf
          weight: 700
